[build-system]
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=6.2",
    "wheel",
    "Cython>=0.29.31",
    "scipy>=1.8",
    "numpy; python_version>='3.9' and platform_python_implementation=='PyPy'",
    "numpy==1.22.4; python_version<='3.10' and platform_python_implementation != 'PyPy'",
    "numpy==1.23.2; python_version=='3.11' and platform_python_implementation != 'PyPy'",
    "numpy>=1.26.0b1; python_version>='3.12'",
]
build-backend = "setuptools.build_meta"

[project]
name = "discretize"
authors = [
    {name = "SimPEG developers", email = "rowanc1@gmail.com"},
]
description = "Discretization tools for finite volume and inverse problems"
requires-python = ">=3.8"
license = {text = "LICENSE"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Natural Language :: English"
]
dependencies = [
    "cython>=0.29.31",
    "numpy>=1.20",
    "scipy>=1.8",
    "setuptools_scm",
]
keywords = [
    "finite volume",
    "discretization",
    "pde",
    "ode"
]
dynamic = ["version","readme"]


[project.urls]
homepage = "http://simpeg.xyz/"
documentation = "https://docs.simpeg.xyz/"
repository = "http://github.com/simpeg/discretize"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
readme = {file = ["README.rst"]}

[tool.setuptools_scm]
write_to = "src/discretize/version.py"

