name: discretize-test
channels:
  - conda-forge
dependencies:
  - numpy>=1.22.4
  - scipy>=1.12

  # optionals
  - vtk>=9
  - pyvista
  - omf
  - matplotlib

  # documentation
  - sphinx==9.1
  - pydata-sphinx-theme==0.19.0
  - sphinx-gallery==0.21.0
  - numpydoc==1.10.0
  - jupyter
  - graphviz
  - pillow
  - pooch

  # testing
  - sympy
  - pytest
  - pytest-cov

  # Building
  - pip
  - meson-python>=0.15.0
  - meson
  - ninja
  - cython>=3.1.0
  - setuptools_scm
