name: discretize-test
channels:
  - conda-forge
dependencies:
  - numpy>=1.22.4
  - scipy>=1.8

  # testing
  - sympy
  - pytest
  - pytest-cov
  - matplotlib

  # Building
  - pip
  - meson-python>=0.14.0
  - meson
  - ninja
  - cython>=3.1.0
  - setuptools_scm
