jobs:
  - job: BuildDocs
    displayName: "Build Documentation"
    pool:
      vmImage: ubuntu-latest
    variables:
      python.version: "3.13"
      doc.build: True
      PYVISTA_OFF_SCREEN: True
      DISPLAY: ":99"
    steps:
      - bash: git fetch --tags
        displayName: Fetch tags

      - bash: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "##vso[task.prependpath]$HOME/.local/bin"
        displayName: Install uv

      - bash: .ci/azure/setup_env.sh
        displayName: Setup discretize environment

      - bash: uv run --no-sync -- make -C docs html
        displayName: "Building HTML"

      - bash: uv run --no-sync -- make -C docs linkcheck
        displayName: "Checking Links"

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "docs/_build/html"
          artifact: "html_docs"
          parallel: true
