jobs:
  - job:
    displayName: Run style checks with ruff
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.11"
      - bash: .ci/install_style.sh
        displayName: "Install dependencies to run the checks"
      - script: ruff check .
        displayName: "Run ruff"