jobs:
  - job:
    displayName: Check version consistency
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.13"
      - bash: pip install pyyaml
        displayName: "Install dependencies to run the checks"
      - script: python .ci/check_version_sync.py
        displayName: "Check versions"

  - job:
    displayName: Run style checks with Black
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.13"
      - bash: .ci/install_style.sh
        displayName: "Install dependencies to run the checks"
      - script: black --check .
        displayName: "Run black"

  - job:
    displayName: Run (permissive) style checks with flake8
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.13"
      - bash: .ci/install_style.sh
        displayName: "Install dependencies to run the checks"
      - script: flake8
        displayName: "Run flake8"
